name: HypixelSkyblockRecreations
main: com.jacksonchen666.hypixelskyblockrecreations.HypixelSkyblockRecreations
author: JacksonChen666
api-version: "1.16"
version: @plugin.version@
description: Hypixel Skyblock recreations.

commands:
  hypixelskyblockRecreations:
    description: A hypixelskyblockrecreations command
    aliases: hsr

permissions:
  HypixelSkybockRecreations.admin:
    default: op
    children:
      HypixelSkybockRecreations.replanting: true
  HypixelSkybockRecreations.replanting:
    description: Replanting item
